### ISSUE TITLE
database design maken

### ISSUE THREAD

**Issue by GeneDrive** [ManoloTonto1/Theater-Baget#14]
gedaan door martijn

**Comment by ManoloTonto1** [comment]
> gedaan door martijn
> 
Assign jezelf en close de issue als hij klaar is, je hoeft niet te zetten dst je het gedaan had.

**Comment by ManoloTonto1** [comment]
**Reopened because tables are missing.**

- Missing bands or groepjes.
- Bij reserveering extra tabel voor de stoelen, reserveering-id, stoel, programmeering-id, rang
- betaling table, customer id, price, discount, reserveering-id
- Donatie tabel: Hoeveelheid, wie, en wanneer.
